#pragma kernel CSMain

RWStructuredBuffer<float4> positionBuffer;

float _Dim;
float _CubeScale;
float3 _Pivot;

[numthreads(1, 1, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float2 uv = float2((id.x % (int)_Dim) / _Dim, floor(id.x / _Dim) / _Dim);
	float x = _Pivot.x + uv.x * _CubeScale * _Dim;
	float y = _Pivot.y + uv.y * _CubeScale * _Dim;
	float z = _Pivot.z;
	float4 pos = float4(x, y, z, _CubeScale);

	positionBuffer[id.x] = pos;
}
